name: Check Specific Reviewer Approval
on:  workflow_dispatch
jobs:
  check-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Необходимо для доступа к файлам репозитория
    
      - name: Read script from file
        id: read_script
        run: |
          echo "script<<EOF" >> $GITHUB_ENV
          cat scripts/approval-check.js >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
    
      - name: Execute script
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: ${{ env.script }}
